### ISSUE TITLE
Laravel Eloquent

### ISSUE THREAD

**Issue by andytruong** [phpvietnam/meetup#10]

**Comment by andytruong** [comment]
Hi @huynhbathanh,

Mọi thứ ổn hỉ? Có trở ngại thì cho tôi biết sớm nhé. Mọi thứ ổn thì chú gửi link đến bài nói chuyện ở đây sớm giùm tôi.

Cảm ơn nhiều ^^

**Comment by huynhbathanh** [comment]
Hi @andytruong !
Ổn, có điều đang bị "dí" quá, chắc tuần sau em mới update tài liệu được. 
Thanks.

**Comment by andytruong** [comment]
:+1:

**Comment by andytruong** [comment]
Ngày mai đó nha chú Thành ơi!

**Comment by andytruong** [comment]
Thank you for great speaking @huynhbathanh (:
