### ISSUE TITLE
Phar

### ISSUE THREAD

**Issue by andytruong** [phpvietnam/meetup#15]
Slide http://slides.com/mrsinguyen/phar#/

**Comment by andytruong** [comment]
Note note note… @mrsinguyen will also talk about http://psysh.org/

**Comment by mrsinguyen** [comment]
The psysh will take in next event, my laptop is still on KCT store, so just talk about Phar only. Thanks

**Comment by andytruong** [comment]
Thank you for great speaking.

**Comment by andytruong** [comment]
http://blog.astrumfutura.com/2015/03/securely-distributing-phars-pitfalls-and-solutions/

**Comment by mrsinguyen** [comment]
Above link is great, thanks for your sharing
