### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by andytruong** [phpvietnam/meetup#18]
## Topics

https://github.com/phpvietnam/meetup/wiki/Ideas
## Structure
1. Time for company recruitment? — 15m?
2. Coupon gifts, how to give?
3. How long for each presentation?
4. …

**Comment by huynhbathanh** [comment]
7. Design pattern

**Comment by huynhbathanh** [comment]
Deployment tools Mina/Capistrano
Deployment to Cloud (Heroku, Google AppEngine, AppFog, AWS...)

**Comment by huynhbathanh** [comment]
Interesting meetup about Scrum (Topic 5) for developers.
http://www.meetup.com/Scrum-Breakfast-Vietnam-Agile-and-Scrum-Meetup/events/221432207/

**Comment by andytruong** [comment]
ReactJS is now really hot!

**Comment by andytruong** [comment]
PHP7
