### ISSUE TITLE
Install and try HHVM with some popular PHP products

### ISSUE THREAD

**Issue by andytruong** [phpvietnam/meetup#19]
- Install HHVM
- Config HHVM fcgi with nginx and Apache
- Demo use HHVM fastCGI to run Drupal and Wordpress.

**Comment by andytruong** [comment]
Hello @mrsinguyen,

Can you arrange your topic in 10 to 15 minutes? Thanks

**Comment by mrsinguyen** [comment]
Yeah, 15 mins is maximum for this.

**Comment by mrsinguyen** [comment]
We should introduction about hhvm-vagrant, it's the fast way to help developers can install & work with hhvm asap.

https://hackpad.com/Install-and-try-HHVM-with-some-popular-PHP-products-vjNG0qX0IGZ

**Comment by and1truong** [comment]
You already forget Docker? :D
