### ISSUE TITLE
Live benchmark Drupal with native PHP and HHVM

### ISSUE THREAD

**Issue by andytruong** [phpvietnam/meetup#21]

**Comment by andytruong** [comment]
Hello @sanglt ,

Can you arrange your topic in 10 to 15 minutes? After speaking, ppl will have an other 10-15m to QA Thanks!

**Comment by sanglt** [comment]
Sure @andytruong 

I'll give you a slide on Sunday :dart:

**Comment by and1truong** [comment]
Thank you guy. There are about 60 ppl are waiting for this. Ha ha
